### ISSUE TITLE
Deployment of SCF on GKE

### ISSUE THREAD

**Issue by rjain15** [SUSE/scf#1641]
Do we have documentation of how to deploy SCF on GKE? 
I am reading the one on kubernetes and AWS / EKE, what changes do I need to make to deploy on GKE?

@viovanov @stevemustafa

**Comment by HartS** [comment]
Hi @rjain15 , we haven't thoroughly vetted our docs there yet, but feel free to take a look at https://github.com/SUSE/scf/wiki/Deployment-on-Google-GKE , and we'd love to know if you hit any issues.

**Comment by drnic** [comment]
It say "required: ubuntu as host OS" - how do you `gcloud container clusters create` and request a specific host OS? I don't see anything mentioned in https://cloud.google.com/sdk/gcloud/reference/container/clusters/create

**Comment by drnic** [comment]
Perhaps update https://github.com/SUSE/scf/wiki/Deployment-on-Google-GKE#cluster-creation with a working `gcloud container clusters create` command, rather than a list of requirements?

**Comment by drnic** [comment]
@troytop pointed me to `--image-type UBUNTU` flag. Until I PR the docs, I've gotten the following commands working on MacOS (see `xargs -I %`):

From @troytop on slack:
```
gcloud container clusters create "${STUDENT}" \
    --zone=europe-west1-d \
    --image-type=UBUNTU \
    --node-locations=europe-west1-d \
    --machine-type=n1-highcpu-16 \
    --num-nodes=1 \
    --addons=HttpLoadBalancing \
    --no-enable-autorepair \
    --no-enable-autoupgrade \
    --project "${PROJECT}"
```

Then to setup cgroups:

```
instance_names=$(gcloud compute instances list --filter=name~$CLUSTER_NAME --format json | jq --raw-output '.[].name')
echo "$instance_names" | xargs -I {} gcloud compute ssh {} -- "sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"console=ttyS0 net.ifnames=0\"/GRUB_CMDLINE_LINUX_DEFAULT=\"console=ttyS0 net.ifnames=0 swapaccount=1\"/g' /etc/default/grub.d/50-cloudimg-settings.cfg"
# Update grub
echo "$instance_names" | xargs -I {} gcloud compute ssh {} -- "sudo update-grub"
# Restart VMs
echo "$instance_names" | xargs gcloud compute instances reset
```

**Comment by drnic** [comment]
I've updated the wikis for SCF + Eirini as much as I can. I'm not sure if/how the following will work for a gcloud get-credentials kubeconfig:
```
 EIRINI_KUBE_CONFIG: 'JSON OF YOUR KUBECONFIG'
```
The kubeconfig for gcloud credentials contains references back to the gcloud CLI:

```yaml
- name: gke_knative-experiments_us-west1-c_knative
  user:
    auth-provider:
      config:
        access-token: ...
        cmd-args: config config-helper --format=json
        cmd-path: /Users/drnic/bin/google-cloud-sdk/bin/gcloud
        expiry: 2018-11-17 22:31:57
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

That is, what Eirini now needs is a gcloud serviceaccount + gcloud CLI in its images.

That is, will Eirini will need to take Google serviceaccount and build its own kubeconfig e.g. https://github.com/starkandwayne/show-me-secrets/blob/master/ci/scripts/lib/kubernetes-target.sh ?
