### ISSUE TITLE
uaa: incorrect identity zone

### ISSUE THREAD

**Issue by poy** [SUSE/scf#1975]
Looking at the `/var/vcap/jobs/uaa/config/uaa.yml` I see the following identity zones:

```
zones:
  internal:
    hostnames:
    - uaa
    - uaa.uaa
    - uaa.uaa.svc
    - uaa.uaa.svc.cluster.local
```

However it looks like the `uaa` service is actually named `uaa-uaa`. This means that the DNS will resolve to `uaa-uaa.uaa.svc.cluster.local` (and not the one listed in the zones).
