### ISSUE TITLE
Mechanism to expose any BOSH property

### ISSUE THREAD

**Issue by viovanov** [SUSE/scf#2766]
As a user of SCF v3, I want to be able to configure any BOSH Job property.
A possible values.yaml:

```
properties:
  instance-group-name:
    job-name:
      some-property: some-value
```
