### ISSUE TITLE
Fix cipher suits and CA trust with upstream loadbalancers

### ISSUE THREAD

**Issue by troytop** [SUSE/scf#3153]
**Describe the bug**
Deploying scf fails when valid certs are configured on an upstream (fronting) load balancer.

**To Reproduce**
Deploy scf or uaa on EKS and add a valid cert to the ELB. Doing this with uaa is the easiest repro.

**Expected behavior**
This should just work.

This is the configuration fix that works around this problem, but it should be the default:

```
bosh:
  instance_groups:
    - name: router
      jobs:
        - name: gorouter
          properties:
            router:
              cipher_suites: ECDHE-ECDSA-CHACHA20-POLY1305:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305:ECDHE-RSA-CHACHA20-POLY1305:TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:ECDHE-RSA-AES256-GCM-SHA384:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:AES128-GCM-SHA256:AES256-GCM-SHA384
            uaa:
              ca_cert: ""
```
This will cause gorouter to trust the system default CAs as well as the internal scf CA.

The uaa.ca_cert must be an empty string (not unset).

There may be a more restrictive suite that would work, but this is safe (Mozilla's recommended cipher suite).
